### ISSUE TITLE
강의 관련 질문은 Issue에 적어주세요.

### ISSUE THREAD

**Issue by rhs0266** [rhs0266/FastCampus#1]
안녕하세요 류호석입니다.

Fast Campus 강의 내용 관련 질문은 [링크](https://github.com/rhs0266/FastCampus/issues)에 `New Issue`를 통해 적어주세요.

**Comment by jiwon83** [comment]
안녕하세요 강의 너무 잘 듣고 있습니다! 다름 아니라 투포인터 문제 중 boj 15565번 귀여운 라이언의 java답안을 참고했는데, 제가 푼거는 ans 를 N+1로 주었는데 왜 -1로 주어야 하는 지 설명 부탁드려도 될까요??
