### ISSUE TITLE
세 용액 2473번 문제 답안이 잘못된 것 같습니다

### ISSUE THREAD

**Issue by kingdom** [rhs0266/FastCampus#10]
안풀려서 답안을 봤는데

첫번째 테스트케이스부터 틀린 답이 나오네요.. 확인 좀 부탁드립니다.

https://github.com/rhs0266/FastCampus/blob/main/%EA%B0%95%EC%9D%98%20%EC%9E%90%EB%A3%8C/02-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98/07~08-%EB%91%90%20%ED%8F%AC%EC%9D%B8%ED%84%B0/%EB%AC%B8%EC%A0%9C%EB%B3%84%20%EC%BD%94%EB%93%9C/2473-%EC%84%B8%20%EC%9A%A9%EC%95%A1/solution.java#L1

**Comment by rhs0266** [comment]
알려주셔서 감사합니다. 수정 완료했습니다.
