### ISSUE TITLE
FastCampus/류호석배 알고리즘 코딩 테스트/제1회/4번-꿈틀꿈틀 호석 애벌레/python 해설

### ISSUE THREAD

**Issue by easyhooon** [rhs0266/FastCampus#104]
정답에 제출해보았는데 맞았습니다(14/39) 로 부분 정답처리됩니다. 
코드의 수정이 필요할것 같습니다

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/51016231/225818921-54b73bef-ea3c-4b74-a196-1fdb86cc6d78.png">

**Comment by rhs0266** [comment]
감사합니다. 수정했습니다!
