### ISSUE TITLE
14502 연구소 해설코드 질문이 있어서 깃헙에 질문 같이 적어놓았습니다. 

### ISSUE THREAD

**Issue by kyoonha** [rhs0266/FastCampus#105]
14502 연구소 해설코드 질문이 있어서 깃헙에 질문 같이 적어놓았습니다. (질문3개)
https://github.com/kyoonha/nn/blob/main/%EC%97%B0%EA%B5%AC%EC%86%8C%20%EC%A7%88%EB%AC%B8111

14502 연구소 23%에서 계속 틀렸습니다 라고나오는데 깃헙에있는 정답코드와 같게 한거 같은데 어디서 에러가 나오는지 이해가 가지 않아서요. 에러코드 올립니다.
https://github.com/kyoonha/nn/blob/main/%EC%97%B0%EA%B5%AC%EC%86%8C%2023%25%EC%97%90%EB%9F%AC

05. 그래프 탐색 (Graph Search, DFS & BFS) - 응용편 1 37분
문제 2251 물통 질문있습니다. 질문은 아래 코드에 적어놓았습니다.(질문6개)
https://github.com/kyoonha/nn/blob/main/%EB%AC%B8%EC%A0%9C%202251%20%EB%AC%BC%ED%86%B5

**Comment by rhs0266** [comment]
제가 답을 어디에 적어 드리면 될까요..?
