### ISSUE TITLE
dp 15991번 1 2 3 더하기 6

### ISSUE THREAD

**Issue by java-saeng** [rhs0266/FastCampus#11]
![image](https://user-images.githubusercontent.com/62413589/124972546-77bb1480-e065-11eb-84b9-7a434d268e26.png)

안녕하십니까 선생님  dp 첫 번째 강의를 듣고 풀어보라고 하시는 문제 중에 1 2 3 더하기 6을 풀다가 질문이 있어 여쭤봅니다.
질문 전에 구글링을 한 뒤, 블로그들의 풀이를 보았지만 와닿는 풀이가 없어 선생님께서는 어떻게 접근하셨을까 궁금해서 이슈 올립니다. 
문제는 이렇게 시도해보았습니다.
![KakaoTalk_20210709_033011614 png](https://user-images.githubusercontent.com/62413589/124973194-31b28080-e066-11eb-8394-03d49d09b8da.jpg)
하지만 i 가 6일 때는 d[0] 값이 필요한데, d[0]은 원래는 0이지 않습니까?? 1 2 3으로 구성되어야하니까요.

물론 포문을 i가 7부터 시작하여 dp[0]을 포함하지 않으면서 풀 수 있지만, 위와 같이 문제를 해결해도 되는지, 올바른 접근 방법인지 궁금합니다. 이 문제에 대해서 설명해보라하면 설명을 하지 못할 것 같아 이렇게 질문을 드립니다..

읽어주셔서 감사합니다.

**Comment by rhs0266** [comment]
d[0] 과 같은 경우는 문제마다 다릅니다. 보통 점화식을 올바르게 만들어주기 위해서 의미를 부여하는 편인데요, 본 문제같은 경우는

d[0] = "0을 1, 2, 3으로 표현하는 경우의 수" 인데, 아무것도 안 더하는 방법이 있다고 생각하고 1을 써주는 것이죠.

아무것도 하지 않는 것도 한 가지 방법이라고 생각하는 겁니다.

**Comment by java-saeng** [comment]
아하 아무것도 하지 않는 것도 한 가지 방법이라고 생각하는군요,, 제가 d[0]을 어떻게 생각했느냐에 따라 문제 설명이 달라질 수 있는 것이고, 틀린 풀이가 아니라는 말씀이신거군요!

**Comment by rhs0266** [comment]
네 맞습니다 ^^ 저도 정확히 똑같이 풀 것 같아요!

**Comment by java-saeng** [comment]
감사합니다 !!
