### ISSUE TITLE
다이나믹 프로그래밍 첫 번째 강의 중 11052 카드 구매하기 문제

### ISSUE THREAD

**Issue by java-saeng** [rhs0266/FastCampus#12]
안녕하십니까 선생님 dp 첫 번째 강의에서 연습 문제 중에 궁금한 점이 생겨 질문 드립니다,,
많은 질문을 드려 죄송합니다.. 이때까지 dp공부를 미루다가 선생님 강의를 통해 꼭 코테 수준까지는 마스터하고 싶어서 이렇게 질문 드립니다

아래의 이미지를 보시면 제가 가짜 문제를 만든 뒤, 1번과 같이 공통점을 찾기 위해 N이 2 ~ 6까지 해보았습니다. 한 2시간 가량 문제를 봐도 규칙성이 전혀 보이질 않았습니다. 그래서 구글링을 통하여 2번과 같은 점화식이란는 것을 알았습니다. 그러나 선생님처럼 가짜 문제를 만든 뒤, 초기값을 구하고 점화식 구해내는 순서로 문제를 해결하고 싶습니다.,, 

 다른 블로그들을 봐도 1번 카드를 살 때 i-1, 2번 카드를 사면  i-2 이런식으로 설명이 되어서 해당 문제의 규칙성은 도대체 어떤 것인지 궁금합니다,,

![image](https://user-images.githubusercontent.com/62413589/125279270-b7784980-e34e-11eb-81a3-15a5950f3a05.png)

별개로 강사님께 여쭙고 싶은게 있습니다,,
제가 강의를 듣고 지금 한 4,5문제 정도 시도를 했는데 거의 90%를 구글링을 하면서 아,, 결국 점화식이 이거였구나.. 라고 하는데 dp는 이렇게 하는 공부가 맞는건가요,,?? 다른 dfs나 bfs 같은 것은 한 4~5문제만 풀어도 아 이런거구나 하고 감이 오는데 dp는 전혀 아니어서요... 감이 1도 안잡힙니다ㅠㅠ 첫 번째 강의도 2번 정도 보고 예제가 확실하게 이해 쏙 박혔는데도 적용을 못하네여,,

**Comment by rhs0266** [comment]
dp는 노가다로 맞아가면서 공부하는 게 맞습니다.

N=6 인 경우까지 손으로 너무 잘 하셨어요! 공통점이 있는 것들끼리 묶어내는 Partition 과정 전까지 잘 하셨다고 보시면 됩니다. 여기서 Partition을 나눈다면, 어떤 공통점끼리 묶어내면 좋을까요?

**Comment by java-saeng** [comment]
완벽 이해됐습니다!
