### ISSUE TITLE
트리파트부터 연습문제 코드

### ISSUE THREAD

**Issue by Kimsunghyunny** [rhs0266/FastCampus#13]
안녕하세요. 강사님 강의 수강중인 수강생입니다.

다름이 아니라 트리파트부터 마지막 파트까지 연습문제에 대한 답 코드가 업로드가 안되어 있는데 업로드 해주실수 있는지 문의드립니다.

구글링해서 다른 코드들 참고할 수 있기도 한데 강사님 코드가 강의 토대로한 코드이기도하고 깔끔해서 도움이 많이 되어서요..

제가 java와 python을 같이 보고있기 때문에 혹시 업로드 해주신다면 python 코드도 포함해서 부탁드리겠습니다!

**Comment by rhs0266** [comment]
코드 열심히 봐주시는 분이 계셨군요!! 감사합니다!

근데 이게 언젠가는 해야하는 일인데 너무 많아서 미루고 있습니다... 금방 ㅎㅎ... 금방 할게요 흑

제3회 모의 코테 종료 되고나서 ㅜㅜ

**Comment by Kimsunghyunny** [comment]
넵 그럼 기다리고 있겠습니다! 감사합니다.
