### ISSUE TITLE
dp2 동물원 

### ISSUE THREAD

**Issue by java-saeng** [rhs0266/FastCampus#15]
선생님 안녕하십니까 
dp 2번째 강의를 듣고나서, 연습문제인 동물원을 풀다가 궁금한 점이 생겼습니다.

문제를 4시간정도 써서 풀어보려고 했습니다. 규칙이 찾아지고, 처음으로 dp 문제를 혼자 힘으로 풀었나해서 신나서 점화식이 정말 생각이 안나는 겁니다.

그래서 구글링을 해보았는데, 대부분 사자가 없을 경우, 왼쪽, 오른쪽에 있을 경우 세 가지를 나눠서 풀었습니다. 구글링을 하여 본 풀이들은 이해가 됐지만, 제 풀이도 맞았습니다로 만들고 싶어서 이렇게 질문드립니다. 점화식을 코드로 작성하진 못했지만, 제 풀이대로 하면 경우의 수가 구글링에서 한 풀이들과 답이 똑같았습니다.

![image](https://user-images.githubusercontent.com/62413589/127030030-31cd185f-2115-4e7f-9eda-69f016661c05.png)

7한테 접근할 수 있는 경우 : 1,2,3,4,6
dp[4][0] += dp[1][0] + dp[1][1] + dp[2][0] + dp[2][1] + dp[3][1]
-> 12

8한테 접근할 수 있는 경우 : 1,2,3,4,5
dp[4][1] += dp[1][0] + dp[1][1] + dp[2][0] + dp[2][1] + dp[3][0]
-> 12

그래서 dp배열을 나타내보면
1 1
2 2
5 5
12 12
입니다.
그리고 나서 dp배열의 모든 원소를 더해준 뒤 +1을 해줍니다.
여기서 +1은 사자가 한 마리도 없을 경우를 생각한 것입니다.

혹시 몰라서 n이 5일 때도 구글에서 맞은 코드를 가져와 시도해보았습니다.
위의 풀이와 이어서 dp[5][0]와 dp[5][1]이 각각 29가 나옵니다. 
그렇다면 29 + 29 + 12 + 12 + 5 + 5 + 2 + 2 + 1 + 1 = 98이 나옵니다.
여기서 +1을 해주면 99로 같은 답이 나오게 됩니다.

제 풀이를 정리하면서 왜 이 풀이는 dp 풀이식으로 적절하지 않은가?
1. 강의대로 dp[N][0] + dp[N][1] 을 더해야 값이 나와야 하는데 제 풀이는 모든 원소를 다 더해서 값을 구해야한다?

2. 점화식을 만드려고 이것저것 다 해보았습니다.,, 정말 귀찮은게 아니라 공통점을 찾으려고 했는데도 이 경우가 맞으면 다른 경우가 안되고 그랬었습니다. 아무튼 점화식을 만들 수 없어서? 
였습니다,, 

꼭 혼자 풀고 싶어서 2~3일 잡고 있었는데, 이제 놓아주고 싶어서 이렇게 강사님께 여쭤봅니다,,
그리고 강사님도 해당 문제를 보고 구글 블로그들과 같이 사자가 없을 경우, 왼쪽, 오른쪽에 각각 있을 경우 세 가지로 나눠서 dp[n][0] dp[n][1] dp[n][2]로 푸셨는지 궁금합니다.

그리고 해당 문제는 계단 오르기로 뭔가 dp 첫번째 강의에서는 규칙성이 눈에 보여서 풀었는데 이번 dp  두번째 강의 중 계단 오르기 관련 연습문제들은 어떠한 특별한 경우를 잘 나눠서 거기 안에서 규칙성을 찾는 것이 포인트 같은데 제가 느낀 것이 맞는지 궁금합니다!!

읽어주셔서 감사합니다

**Comment by rhs0266** [comment]
dp[i][j] 의 정의가 어떻게 되시나요?

**Comment by java-saeng** [comment]
i 번째 줄 , j칸에 사자가 들어갈 수 있는 경우의 수입니다.

**Comment by java-saeng** [comment]
계속 생각해봤는데 제가 말씀드린 dp 정의가 말이 이상한 것 같습니다,,
규칙이 눈에 보였는데 문제가 풀리지 않아서 계속 붙잡고 있었던 것 같기도 합니다,,
값을 구할 때, i = N일 때, 답이 나와야하는데 애초에 잘못 생각했던 것 같습니다,,

**Comment by rhs0266** [comment]
말씀하신 방법으로 하면 적어주신 방법이 정답이 맞습니다. 올바르게 생각하신 거 맞아요!

다만 말씀하신 것처럼 i 가 커질수록 더해야 하는 게 많아지죠? 그 이유는 "i-1 번 줄에 사자가 한 마리도 없는 경우" 를 dp[i-1][0] 이나 dp[i-1][1] 로는 절대로 알 수 없기 때문입니다. 왜냐하면 dp[i-1][0]이나 [1] 모두 사자가 무조건 존재해야 하기 때문이죠.

저같은 경우는 j=2 인 경우를 새로 만들 것 같습니다.

dp[i][0] = 1번~i번 행에 사자를 올바르게 나열하는 방법들 중에서, i 번행 0 번 열에 사자가 있는 경우
dp[i][1] = 1번~i번 행에 사자를 올바르게 나열하는 방법들 중에서, i 번행 1 번 열에 사자가 있는 경우
dp[i][2] = 1번~i번 행에 사자를 올바르게 나열하는 방법들 중에서, i 번행에 사자가 전혀 없는 경우

이렇게 만들면 아마 고민하셨던 "식이 너무 길다" 가 해결되실 것 같아요.

**Comment by java-saeng** [comment]
손으로 하나씩 다 써보니까 제가 했던 방법은 말씀하신대로 사자가 아예 없을 경우는 뺀 경우의 수를 구하게 되네요

저는 마지막 +1 해주는 것이 사자가 없을 경우를 생각해서 더해준 것인데, 이 말은 즉, 전체에 사자가 없을 경우이지, 행마다 사자가 없는 경우를 더해준 적이 없는 것 같습니다. 그래서 +1한게 우연이 맞은 것 같네요,,

구글링과 다른 풀이법을 생각한 줄 알고 계속 붙잡고 있었는데 아니었군요,,, 도대체 dp는 감이 안잡히네요!!!! 
읽어주셔서 감사합니다!! 해결됐어용 ㅎㅎ

ps. 혹시 선생님 강의 하시는 것이나 질문에 답해주신 풀이들 정리해서 블로그에 올려도 되나요,,, 출처는 깃헙주소로 밝히겠습니다. 예를 들어, 그래프 단원을 듣고 인접행렬, 인접리스트가 있고, 거기에 시간복잡도와 장단점, bfs는 언제 사용하는 지 등 pdf 그대로가 아닌 제 말로 해석해서 쓰고싶은데 혹시 가능할까요??

**Comment by rhs0266** [comment]
넵 상관없습니다!

**Comment by her0807** [comment]
@java-saeng 

안녕하세요. 저도 동물원 알고리즘으로 오늘 2시간 정도를 소요했는데요, 

제가 비교적 간단한 점화식을 찾아내서 댓글 남깁니다.
기존에 강사님께서 도출하셨던 간단한 방법인데요, 


n =1 일 때는 사자가 없거나, 왼쪽에 있거나 오른쪽이 있거나 해서 `n =1 경우의 수가 3` 입니다.

n = 2 일 때는  `n =2 경우의 수 7` 입니다.

n = 3 일 때는  `n =2 경우의 수 17` 입니다.

그리고 문제에서 `n =4 경우의 수 41` 을 주었으니 이 4개의 상관 관계를 따져보면

n 이 3 일때 `dp[n-2] +  (dp[n+1]*2)` 를 하게되면 `3+ (7*2) = 17 `이 됩니다. 

이 식을 참고해서 푸니 

```java
    private static void pro() {
        dp[1] = 3 % 9901;
        if(N>2) {
            dp[2] = 7 % 9901;
        }
        for (int i = 3; i <= N; i++) {
            dp[i] = (dp[i - 2] + (dp[i - 1] * 2)) % 9901;
        }
        System.out.println(dp[N] % 9901);
    }
```
이렇게 하면 풀리더군요. if 문을 걸어놓은 이유는, 만약 N = 1 일 경우에 오버플로우가 나서 방지하기 위함입니다! 

제 코드도 참고해서 생각해주시면 감사하겠습니다 ㅎㅎ 

그럼 즐거운 코딩 하세요 :)

**Comment by java-saeng** [comment]
@her0807
이차원 배열 이용한 풀이는 직관적이어서 쉬운데 
일차원 배열이 생각하기 어렵군요 
코드 공유 감사드립니다.
