### ISSUE TITLE
14502 연구소

### ISSUE THREAD

**Issue by java-saeng** [rhs0266/FastCampus#18]
선생님 안녕하십니까 
그래프 2 강의에서 연구소 문제에서 궁금한 것이 생겨 질문드립니다.
![image](https://user-images.githubusercontent.com/62413589/127814217-a19bdc2f-59ac-45df-bba6-0ac05e9f3c10.png)

이 부분이 조합 부분이지 않습니까?
벽이 1 2 3 4가 있으면
1 2 3, 1 2 4, 1 3 4 이런 식으로 하는건데  이렇게 푸는 것을 처음 봐서 여쭤보게 되었습니다.

N과 M에서 조합 부분을 풀 때, visit[i] = true하고 dfs돌리고 visit[i] = false하는 백트래킹이 있지 않습니까? 그거랑 똑같은건지 궁금합니다,,

**Comment by rhs0266** [comment]
네 맞습니다. idx 를 하나씩 증가시키면서 `idx 번째 벽을 선택할 지 말 지`를 결정하고 idx+1 번째에 대해 반복시키는 함수입니다.

**Comment by java-saeng** [comment]
조합을 이렇게도 구하는 군요,,, 감사합니다!! N과 M을 풀면서 한 번 써봐야겠습니다
