### ISSUE TITLE
실제 문제 푸실때도 스케치 진행 여부 질문

### ISSUE THREAD

**Issue by JinSungHwang** [rhs0266/FastCampus#23]
안녕하십니까 류호석님
패캠 java369 수강생입니다 

고퀄리티의 강의를 찍어주셔서 감사합니다

류호석님의 문제 해설 강의를 볼때 항상 구현할 함수에 주석으로 스케치를 하신것을 많이 볼 수 있었습니다
이것이 강의를 찍기위해서가 아니라 류호석님도 실제로 구현시 그렇게 스케치를 진행하고 문제를 푸시나요??
문제풀기전에 솔루션 접근 방법이나 시간 복잡도와 공간 복잡도를 계산하는 정도까지는 알겠는데 주석으로 스케치까지 실제로 진행하시는지가 궁금합니다

**Comment by rhs0266** [comment]
주석은 코드를 짜기 전 / 짜는 도중 / 짜고난 후에 따라 성격이 다른 것 같아요.

짜기 전에 모든 주석을 다 쓸 수 있다? 고수가 초보 교육을 하는 상황입니다.
자기 난이도에 맞는 문제를 풀 때는 "짜는 도중"에 헷갈리는 부분에 있어서 필요한 부분만 작성하는 편이 좋다고 생각합니다.

저도 백준 다이아, 루비 풀 때는 주석 난무하게 구현하고 있습니다 ㅎㅎㅎ 수강생분께서도 자기 난이도에 맞는 문제를 푸시는 거라면 짜기 전에는 무리이더라도 짜는 도중에 중간중간 헷갈릴 때, 코드를 작성하기 전에 구어체로 먼저 주석을 작성하시면 도움이 되실 거에요!

**Comment by JinSungHwang** [comment]
@rhs0266 
짜는 도중 헷갈리는 부분을 주석으로 짜신다고 하셨었는데 그런것은 예를 들면 어떤것들이 있을까요??
사실 저는 지금 뭐가 헷갈리고 뭘 모르는지도 모르는 상태라서 귀찮으시더라도 조금 더 답변해시면 감사하겠습니다

**Comment by rhs0266** [comment]
예를 들면 백준 16235번 나무 재테크의 경우에는 봄, 여름, 가을, 겨울 이라는 패턴이 존재하고 그 안에서 각각 복잡한 작업이 있으며, 동시에 이걸 for문으로 감싸기까지 해야하기 때문에 안 봐도 길어질 걸 압니다. 헷갈리지 않기 위해서 본격 코딩 시작 전에 모듈화를 시켜놓고 주석으로 `// 봄: 나무가 자신의 나이만큼 양분을 먹고, 나이가 1 증가한다.` 같은 걸 적어두는 거죠.

백준 19238번 스타트 택시의 경우도 해보시면 아시겠지만 짤 게 많습니다. 마찬가지로 모듈화를 종이에 그려가면서 미리 하고,  코딩 때는 모듈마다 주석으로 역할을 적어주는 거죠. 그럼 실제 코딩하기 정말 편할 거에요!

**Comment by JinSungHwang** [comment]
정말 상세한 답변 감사합니다^^
강의 중간 중간 말씀해주시는 소중한 팁과 더불어서 이 답변해주시는것도 최대한 잘 활용해보겠습니다
감사합니다!!!
