### ISSUE TITLE
연습 문제 중 배열 합치기

### ISSUE THREAD

**Issue by java-saeng** [rhs0266/FastCampus#25]
강사님 안녕하십니까 이번엔 두 포인터 강의 듣고있습니다.
기본 문제를 풀면서 문제를 맞더라도 강사님 코드를 한 번 더 보고 익히는데,
두 포인터에서 배열 합치기 문제의 코드가 부분합 코드와 매우 유사해보여 질문드립니다.

혹시 맞다면 강사님의 배열 합치기 코드를 보고싶습니다.

**Comment by rhs0266** [comment]
앗 제가 뭔가 잘못 올렸을 수도 있습니다. 확인해보겠습니다!

**Comment by rhs0266** [comment]
제대로 수정했습니다. 감사합니다.
