### ISSUE TITLE
정렬파트 카드 문제 질문드립니다!

### ISSUE THREAD

**Issue by hyeonuk-kor** [rhs0266/FastCampus#29]
안녕하세요?
카드 문제의 Arrays.sort()의 경우 long 타입이어서 시간 복잡도가 N^2이 나올 것 같은데,
강의 내용과 같이 N log N이 맞는지 궁금하여 질문드립니다!

**Comment by rhs0266** [comment]
음..? Arrays.sort가 long 타입이면 왜 N^2 이 되나요?

**Comment by hyeonuk-kor** [comment]
long은 primitive type로 알고있는데, 
n log n을 보장하는 tim sort가 아니기때문에 
worst case로 N^2까지 고려되어야하는 것이 아닌지 
문득.. 궁금해서 질문드렸습니다!

**Comment by rhs0266** [comment]
아하 최악의 경우를 말씀하신 거군요. 굳..이 따지자면 그렇겠네요!
