### ISSUE TITLE
문제 풀이 질문드립니다.

### ISSUE THREAD

**Issue by hyeonuk-kor** [rhs0266/FastCampus#35]
안녕하세요? 물통과 비슷한 문제가 있어서 아래와 같이 문제를 해결해봤습니다.
혹시 잘못된 부분(ex: 시간복잡도)이나 리팩토링이 필요한 부분이 있는지 알아보기 위해 Issues에 글을 남기게 됐습니다.

# 백준 - 소수 경로

https://www.acmicpc.net/problem/1963

소수를 유난히도 좋아하는 창영이는 게임 아이디 비밀번호를 4자리 ‘소수’로 정해놓았다. 어느 날 창영이는 친한 친구와 대화를 나누었는데:

“이제 슬슬 비번 바꿀 때도 됐잖아”
“응 지금은 1033으로 해놨는데... 다음 소수를 무엇으로 할지 고민중이야"
“그럼 8179로 해”
“흠... 생각 좀 해볼게. 이 게임은 좀 이상해서 비밀번호를 한 번에 한 자리 밖에 못 바꾼단 말이야. 예를 들어 내가 첫 자리만 바꾸면 8033이 되니까 소수가 아니잖아. 여러 단계를 거쳐야 만들 수 있을 것 같은데... 예를 들면... 1033 1733 3733 3739 3779 8779 8179처럼 말이야.”
“흠...역시 소수에 미쳤군. 그럼 아예 프로그램을 짜지 그래. <b>네 자리 소수 두 개를 입력받아서 바꾸는데 몇 단계나 필요한지 계산</b>하게 말야.”
“귀찮아”
그렇다. 그래서 여러분이 이 문제를 풀게 되었다. 입력은 항상 네 자리 소수만(1000 이상) 주어진다고 가정하자. 주어진 두 소수 <b>A에서 B로 바꾸는 과정에서도 항상 네 자리 소수임을 유지</b>해야 하고, ‘네 자리 수’라 하였기 때문에 0039 와 같은 <b>1000 미만의 비밀번호는 허용되지 않는다.</b>

##### 예제 입력 1

```
3
1033 8179
1373 8017
1033 1033
```

## 구현 방법

- 첫 번째 소수에서 각 자리를 하나씩 바꿔가며, 두 번째 소수까지의 <b>모든 경우</b>를 탐색한다.
- 소수를 만족하는 네 자리수는 하나의 정점으로 보고, 자리를 바꾸는 행위가 간선을 통해 이동하는 것으로 볼 수 있다.
- 따라서 정점과 간선을 구현할 수 있는 Graph를 배열로 구현해볼 수 있다.
- 만들 수 있는 경우가 여러가지 존재할 수 있고, 그 중 최소한의 단계를 구하기 위해 <b>BFS</b>를 이용하여 문제를 해결한다.
- 시간 복잡도는 각 자리가 0~9까지 올 수 있으므로 O(10^4)가 된다.

메모리 : 28044kb, 시간 : 344ms

 - http://boj.kr/ce671e7ac5b642a3a6fe32d48bfc5ed2

#### 변수 설명

- 소수 쌍의 수를 입력받기 위해 정수형 N을 선언한다.
- 각 줄에 소수들을 문자열 형식으로 입력받기 위해, 2차원 String 배열을 선언한다. 
 - 각 자리(1의 자리, 10의 자리, 100의 자리, 1000의 자리)를 0부터 9까지 하나하나 바꿔가며 탐색하기 위함
- 한 번 검사했던 소수는 재검사하지 않기 위해, visit 배열을 선언한다.

##### solve() 함수

- 테스트케이스를 입력받고, 모든 케이스에 대한 정답을 계산하는 함수
- 매 케이스마다 visit 배열을 초기화해준다.
- 첫 번째 소수에서 두 번째 소수로의 변환을 의미하는, to와 from 변수를 만들어 입력받았다.
- 이를 bfs 함수의 매개변수로 각각 전달하고, 그 결과를 출력해준다.

##### bfs() 함수

- 매개변수(String to, String from)을 입력받아, to에서 from으로 총 몇 단계에 걸쳐 갈 수 있는지 계산하는 함수
- to 문자열이 from가 같아지면 bfs함수를 종료한다.
- from에서 to로 바꾸는 과정에서, 바꿀 수 있는 수와 없는 수를 구분하기 위한 함수(isPossible)를 호출
 - 바꿀 수 있을 때만 큐에 넣어, BFS를 진행한다.

##### isPossible() 함수

- 매개변수(String number)를 숫자로 변환하여, BFS 탐색이 가능한지 알려주는 함수
 - 1000 미만의 수라면 false를 반환한다.
 - 이미 방문(visit 배열 활용)했다면 false를 반환한다.
 - 소수 판별 함수(isPrime)의 결과를 반환한다.
 - 위에서 false가 반환되지 않았다면, 가능한 수이므로 true를 반환한다.

##### isPrime() 함수

- 매개변수(int number)의 수가 소수인지 확인하는 함수
 - 최소 소수인 2부터 number-1까지 탐색하여 나눠떨어지면 false를 반환한다.
 - number-1까지 나눠 떨어지는 수가 없었다면, 소수이므로 true를 반환한다.

**Comment by rhs0266** [comment]
오... 친절한 설명까지 감사드립니다 ㅎㅎ

1. `isPrime()` 함수를 다음과 같이 바꿔보세요.
```java
boolean isPrime(int number) {
	for(int i=2; i * i < number; i++) {
		if(number%i==0)
			return false;
	}
	return true;
}
```

2. 4자리 숫자를 문자열로 다루기 위해 들어간 coding effort가 그로 인해 얻어진 profit보다 현저히 비쌉니다. String과 Integer가 서로 꽤 자주 convert 되고 있는데, 4자리라는 점을 이용하면 수학적으로 충분히 해결이 가능하긴 합니다. 물론 이걸 다시 Integer only로 바꾸더라도 실행 시간이 유의미하게 바뀔 것 같진 않긴 합니다..!!

3. 저도 안 해본 것이라 장담하긴 힘든데, 모든 간선을 TC를 처리하기 이전에 preprocess로 미리 구해놓으면 BFS 함수 부분이 더 이뻐질 것 같긴 해요 ㅎㅎㅎ 실행 시간면에서 이득일 지는 확신이 없네요 ㅜㅜ

**Comment by rhs0266** [comment]
아 죄송합니다 등호를 빼먹었네요...
```
boolean isPrime(int number) {
	for(int i=2; i * i <= number; i++) {
		if(number%i==0)
			return false;
	}
	return true;
}
```

**Comment by hyeonuk-kor** [comment]
저정도는 제가 발견했어야했는데 아직 부족한가봅니다 ㅠㅠ
잘 알려주셔서 감사합니다!
