### ISSUE TITLE
p15970 화살표 그리기 질문입니다.

### ISSUE THREAD

**Issue by syoung622** [rhs0266/FastCampus#41]
제출번호 35000475

위의 제출번호의 코드에서는 틀렸습니다.로 나오는데 주어진 예시는 다 맞는데 왜 틀린건지 전혀 모르겠습니다ㅠㅠ 

코드
`
import java.util.*;

//화살표 그리기
public class Main {
	
	static int n;
	static int ans=0;
	static int[][] point;

	public static void main(String[] args) {
		
		Scanner sc = new Scanner(System.in);
		
		n=sc.nextInt();
		
		point=new int[n][2];
		
		for(int i=0;i<n;i++) {
			
			point[i][0]=sc.nextInt();
			point[i][1]=sc.nextInt();
			
		}
		
		pro();
		
		System.out.println(ans);
		
		// TODO Auto-generated method stub

	}
	
	static void pro() {
		
		for(int idx=0;idx<n;idx++) {
			//흰색
			if(point[idx][1]==1) {
				
				int tmpans=Integer.MAX_VALUE;
				for(int i=0;i<n;i++) {
					if(point[i][1]==1) {
						if(Math.abs(point[i][0]-point[idx][0])==0) continue;
						tmpans=Math.min(tmpans, Math.abs(point[i][0]-point[idx][0]));
					}
				}
				if(tmpans==Integer.MAX_VALUE) continue;
				
				ans+=tmpans;
				
			}
			//검은색
			else {
				
				int tmpans=Integer.MAX_VALUE;
				for(int i=0;i<n;i++) {
					if(point[i][1]==2) {
						if(Math.abs(point[i][0]-point[idx][0])==0) continue;
						tmpans=Math.min(tmpans, Math.abs(point[i][0]-point[idx][0]));
					}
				}
				
				if(tmpans==Integer.MAX_VALUE) continue;
				
				ans+=tmpans;
			}
		}
		
	}

}
`

**Comment by rhs0266** [comment]
아이고 ㅜㅜㅜ 문제 입력 부분을 제대로 읽어주세요. 색깔은 검, 흰 두 가지만 존재하는 것이 아닙니다. 예제만 그런 것입니다.
