### ISSUE TITLE
선 시청 후 문제풀이 vs 선 도전 후 시청

### ISSUE THREAD

**Issue by Gunggo** [rhs0266/FastCampus#43]
안녕하세요 강사님!
먼저 양질의 강의에 대해 정말 감사드립니다!

질문은 제목과 같습니다!
수강 후 문제풀이 도중 재 수강 VS 도전 후 풀이보고 재도전 후 재 수강

강사님은 어떤 방식을 추천하시는지 궁금합니다!

**Comment by rhs0266** [comment]
안녕하세요! 시청해주셔서 감사드립니다 ㅎㅎㅎ

무조건 후자가 이득이라고 생각하지만, 상황에 맞게 조절하시면 좋을 것 같아요. 지금 당장 급한 면접이 있다면 전자를 선택하셔야겠죠? 다만 올바르게 이해 했는지 필요할 것이고, 가능하면 후자를 추천 드립니다.

그 이유는, 풀이를 바로 보시면 놓치는 게 많기 때문이에요. 이 문제가 왜 어렵고, 자기만의 풀이는 어땠는데 강의에서는 어떤 부분에서 다르게 접근 했는 지를 알기 편합니다. 또한 정답 코드 이해도 훨씬 수월하실 것입니다.

**Comment by Gunggo** [comment]
시간적 여유가 있는 상황이라 조금 더 걸리더라도 내 풀이와 강사님 풀이를 비교하는쪽으로 해야겠네요!
답변 정말 감사드립니다!!!
