### ISSUE TITLE
BOJ 13702 : 이상한 술집 풀이 0 나누기 오류 관련

### ISSUE THREAD

**Issue by xtozero** [rhs0266/FastCampus#46]
안녕하세요.
좋은 강의 감사히 보고 있습니다.

이분탐색 연습 문제인 이상한 술집을 풀면서 의문이 생겨 파이썬 풀이를 보았습니다.
문제를 읽어 보았을 때 아래와 같은 입력도 가능하다고 생각되는데요. ( 막걸리의 용량은 231 -1 보다 작거나 같은 자연수 또는 0이라는 조건 때문에 )

1 1
0

과 같은 입력에서 해당 풀이는 0 나누기 오류가 발생할 것으로 생각됩니다.
혹시 제가 질문을 잘 못 이해했다면 너른 양해 부탁드립니다.
감사합니다.

**Comment by rhs0266** [comment]
오. 맞습니다. 이건 백준에 제보하시면 많이들 틀리겠네요!
