### ISSUE TITLE
20363 부동산 답안 질문드립니다!

### ISSUE THREAD

**Issue by bangddong** [rhs0266/FastCampus#47]
답안 코드가 도저히 이해가 안되서 질문 남깁니다!

pro 메소드 부분이 좀 이상한 것 같은데
혹시 정상적인 코드가 맞을까요 ...?

**Comment by rhs0266** [comment]
네 맞습니다. 뭐가 이상한가요?

**Comment by bangddong** [comment]
애매하게 질문드려 죄송합니다!

static void pro() {
        // 사고 싶은 땅에서 시작해서 루트 땅까지 올라오면서 정답을 찾으면 편하다.
        // 왜냐하면 부모 노드는 찾기 쉽기 때문이다.
        while (Q-- > 0){
            int x = scan.nextInt(), res = 0;
            int y = x;
            while (x) {
                if (estate[x]) res = x;
                x >>= 1;
            }
            estate[y] = 1;
            sb.append(res).append('\n');
        }
        System.out.println(sb);
    }

이 메소드 내부에서
while (x) 와 if (estate[x]) 부분이 이해가 안됩니다!
x도 int형이고 estate 또한 int 배열인데 조건문에 들어갈 수 있나요 ...?

java 문법적인 질문이라 혹시 몰라 IDE에 그대로 카피해도 오류가 발생합니다!

**Comment by rhs0266** [comment]
아 뭔가 코드에 조금의 누락이 있었네요 ㅜㅜ 죄송합니다. 바로 수정해드릴게요!

**Comment by bangddong** [comment]
빠른 피드백 정말 감사드립니다!!!
