### ISSUE TITLE
Inner class인 FastReader class에 대한 질문

### ISSUE THREAD

**Issue by Ting-Kim** [rhs0266/FastCampus#49]
안녕히세요 강사님! 강의 너무 잘 들으며 도움 많이 받고 있습니다. 감사합니다!

다름 아니라, 강사님의 코드에서 `FastReader` 클래스를 내부 클래스(정적 멤버 클래스)로 구현하여, 데이터를 입력 받을 때 사용하고 계십니다.
이게 `static class`로 구현하신 점은 `Effective Java` 책을 통해서 이해를 했는데, **해당 `FastReader`에 구현된 멤버 필드와 메서드(`bufferedReader`, `stringTokenizer`, `next()`, `nextInt()` 등..)는 `static`으로 구현하지 않으신 이유가 궁금합니다.**
(모두 `static`으로 선언해도 풀리긴 하더라구요..! 성능이나 다른 문제가 있을 수 있어서 인지 너무 궁금합니다!)

어떻게 보면 문제에 대한 질문일 수도, 단순 Java 기본에 대한 내용인 질문일 수도 있을 것 같습니다만, 부족한 제게 가르침을 주신다면 너무 감사할 것 같습니다!

항상 감사합니다. 좋은 하루 되세요 :)

**Comment by rhs0266** [comment]
안녕하세요 @Ting-Kim 님. 강의 재밌게 들어주셔서 감사합니다 ㅎㅎ

성능에 큰 차이는 없습니다. 한 가지 상정할 수 있는 시나리오는 다음과 같습니다.

- 입력 stream이 여러 가지가 있을 때, `FastReader` object를 다수 만들어야 합니다.

사실 PS 에서는 일어나지 않을 시나리오라 상관없습니다 :)

사소한 부분일지라도 놓치지 않고 궁금해하시는 게 보기 조으네용
