### ISSUE TITLE
1182 부분수열의 합 질문

### ISSUE THREAD

**Issue by yanJuicy** [rhs0266/FastCampus#50]
![image](https://user-images.githubusercontent.com/43159295/149663085-6424b5a6-b93e-480f-ac48-2974304a44a3.png)

부분 수열의 개수 상한이 2^20이라는건 어떻게 계산하는건가요

**Comment by rhs0266** [comment]
부분 수열은 배열의 원소를 부분적으로 선택하는 것과 같습니다.

따라서, 원소마다 "부분 배열에 넣는다" vs "부분 배열에 안 넣는다" 를 선택할 수 있습니다. 결국 각 원소마다 선택하냐 마냐를 결정하는 2 가지 선택지가 있으므로 원소가 1개면 전체 경우는 2^1 가지, 2개면 2^2 가지, 3개면 2*2*2=2^3 가지, N개면 2^N 가지 가 됩니다.

원소가 20개가 주어지므로, 2^20 가지의 부분 수열이 존재할 수 있다고 생각하시면 됩니다. 이해가 가시나요?

**Comment by yanJuicy** [comment]
넵 감사합니다~
