### ISSUE TITLE
배열의 크기 설정에 대한 질문

### ISSUE THREAD

**Issue by Ting-Kim** [rhs0266/FastCampus#51]
안녕하세요! 강의 정말 잘 들었습니다. 감사합니다 :)

레포지토리에 올라와 있는 추천 문제를 풀다가 [`BOJ.2251 물통`](https://www.acmicpc.net/problem/2251) 문제에 대한 풀이 코드를 보게 되었습니다.
[(패캠 풀이코드 링크)](https://github.com/rhs0266/FastCampus/blob/main/%EA%B0%95%EC%9D%98%20%EC%9E%90%EB%A3%8C/02-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98/09~11-%EA%B7%B8%EB%9E%98%ED%94%84%20%ED%83%90%EC%83%89/%EB%AC%B8%EC%A0%9C%EB%B3%84%20%EC%BD%94%EB%93%9C/2251-%EB%AC%BC%ED%86%B5/solution.py)
간단한 궁금증인데, 배열의 크기를 `205`로 초기화 하신 점입니다.
  ```python
  # 풀이 코드 중..
  visit = [[[False] * 205 for _ in range(205)] for _ in range(205)]
  possible = [0] * 205

  # ..
  ```

문제에서의 조건은 `1<=A, B, C<=200` 이기 때문에, 저는 `201`을 생각했는데 `205`로 잡은 이유가 있으실까요?
(강의와 연관없는 질문이라면, 죄송합니다! 😢)

항상 감사드립니다!

**Comment by rhs0266** [comment]
개인 성향입니다! 문제를 풀다보면 종종 N+2, N+3 번지에 접근하는 일도 있었어서 넉넉하게 5 정도 더하는 편입니다 :)

201도 가능합니다. 올바르게 이해하셨습니다!
