### ISSUE TITLE
연습문제 답안 링크가 잘못되어 있습니다.

### ISSUE THREAD

**Issue by minsssg** [rhs0266/FastCampus#52]
다이나믹 프로그래밍 문제 중

"1,2,3 더하기 3"의 정답 링크 코드가 "1,2,3 더하기 6"의 정답 코드 인 것 같습니다.

링크가 잘못 연결된 것 같습니다.

감사합니다.

**Comment by rhs0266** [comment]
아이고 6에 대한 정답 코드를 아직 안 올렸군요. 감사합니다 :)

**Comment by rhs0266** [comment]
1, 2, 3 더하기 3 까지 수정 완료했습니다! 감사합니다.
