### ISSUE TITLE
이분탐색 문제 2343번 관련 질문입니다.

### ISSUE THREAD

**Issue by S-Onix** [rhs0266/FastCampus#53]
import java.io.*;
import java.util.Arrays;
import java.util.StringTokenizer;

public class BOJ2343 {

    static int N,M;
    static int [] lessons;

    static void input(){
        FastScan fc = new FastScan();

        N = fc.nextInt();
        M = fc.nextInt();

        lessons = new int [N];
        for(int i =0; i < N; i++) {
            lessons[i] = fc.nextInt();
        }
    }

    static boolean determination(int len) {
        int cnt = 1, sum = 0;
        for (int i = 0; i < N; i++) {
            if (sum + lessons[i] > len) {
                cnt++;
                sum = lessons[i];
            } else {
                sum += lessons[i];
            }
        }
        return cnt <= M;
    }

    static void solve(){
        Arrays.sort(lessons);

        int L = lessons[N-1];
        int R = 1000000000;
        int result = 0;

        while(L<=R) {
            int mid = (L+R) / 2;
            if(determination(mid)) {
                result = mid;
                R = mid - 1;
            }else {
                L = mid + 1;
            }
        }

        System.out.println(result);
    }

    public static void main(String[] args) {
        input();
        solve();
    }

    static class FastScan{
        BufferedReader br;
        StringTokenizer st;

        public FastScan(){
            br = new BufferedReader(new InputStreamReader(System.in));
        }

        public FastScan(String name) throws FileNotFoundException {
            br = new BufferedReader(new FileReader(name));
        }

        String next() {
            while (st == null || !st.hasMoreElements()) {
                try {
                    st = new StringTokenizer(br.readLine());
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
            return st.nextToken();
        }

        int nextInt() {
            return Integer.parseInt(next());
        }

        long nextLong() {
            return Long.parseLong(next());
        }

        double nextDouble() {
            return Double.parseDouble(next());
        }

        String nextLine() {
            String str = "";
            try {
                str = br.readLine();
            } catch (IOException e) {
                e.printStackTrace();
            }
            return str;
        }
    }
}

와 같이 코드를 작성하여 백준에 제출했는데 틀렸다고 나오고 있습니다...
답안과 비교해본 결과 배열 인덱스 설정부분과 L값 설정부분을 제외하고는 동일한것으로 보이는데... 어떤 케이스에 틀렸는지 감이 오지 않아 질문드립니다.

**Comment by rhs0266** [comment]
`determination` 함수의 구현의 기저에는 "`len`보다 큰 lesson 값은 존재하지 않는다" 라는 가정이 있습니다.
```
if (sum + lessons[i] > len) {
    cnt++;
    sum = lessons[i];
}
```

이 부분을 말로 설명하면, "lessons[i]를 위해 새로운 블루레이를 만들고 lessons[i]를 그 곳에 저장한다"가 됩니다. 하지만 lessons[i]가 len 보다 크게 된다면, 이는 말이 안되는 상황이죠? `L`값을 lessons[N-1]로 놓고 시작하시는데, 만약 이 값이 너무 작다면, 위와 같은 전제가 깨지게 됩니다.

따라서 아래 부분과 같이 determination 함수를 변경해주시면 될 것 같습니다.

static boolean determination(int len) {
    int cnt = 1, sum = 0;
    for (int i = 0; i < N; i++) {
        if (lessons[i] > len) {
            return false;
        }
        if (sum + lessons[i] > len) {
            cnt++;
            sum = lessons[i];
        } else {
            sum += lessons[i];
        }
    }
    return cnt <= M;
}
