### ISSUE TITLE
안녕하세요. 완전 탐색 관련 질문 드립니다.

### ISSUE THREAD

**Issue by snape016** [rhs0266/FastCampus#56]

**Comment by snape016** [comment]
재귀 함수에 if(k == n) 혹은 if(k ==n+1) 의 조건문을 만들 때 n과 n+1을 하는 기준이 있을까요?

**Comment by rhs0266** [comment]
k 가 가지는 의미에 따라 달라질 것 같습니다.
- "1~k 까지 모두 다뤘다" => k==n 이 곧 종료조건
- "1~k-1 까지 모두 다루고, 이제 k번째에 대해 다룰 예정이다" => k==n+1 이 곧 종료조건
