### ISSUE TITLE
7795.먹을 것인가 먹힐 것인가 - 시간 초과 관련 문의

### ISSUE THREAD

**Issue by snape016** [rhs0266/FastCampus#57]
아래의 소스가 시간 초과가 나는데 혹시 어떤 점 때문에 그런지 알 수 있을까요??

import java.io.IOException;
import java.util.Arrays;
import java.util.Scanner;

public class Main {
	static Scanner sc = new Scanner(System.in);
	
	static int n,m;
	static int[] a,b;
	
	public static int lower_bound(int[]bb, int L, int R, int X) {
		
		
		int res = L-1;
		for(int i=1; i<=m; i++) {
			int mid = (L+R) / 2;
			if(bb[mid] < X) {
				res = mid;
				L = mid + 1;
			} else {
				R = mid - 1;
			}
		}
		return res;

	}
	
	public static void sort()  {
		Arrays.sort(b, 1, m+1);
		int result = 0;
		for(int i=1; i<=n; i++) {
			result += lower_bound(b, 1, m, a[i]);
		}
		
		System.out.println(result);

		
	}
	public static void input() {
		n = sc.nextInt();
		m = sc.nextInt();
		
		a = new int[n+1];
		b = new int[m+1];
		
		for(int i=1; i<=n; i++) {
			a[i] = sc.nextInt();
		}
		for(int i=1; i<=m; i++) {
			b[i] = sc.nextInt();
		}
	}
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int t = sc.nextInt();
		
		while(t-->0) {
			input();
			sort();
		}
	}

}

**Comment by rhs0266** [comment]
프로그램의 전체 수행 시간은 `입력 시간 + 알고리즘 수행 시간 + 출력 시간` 입니다. 알고리즘은 잘 짜셨어도 입력이나 출력이 오래 걸리면 시간 초과가 발생합니다. 빠른 입출력을 공부해보세요!
