### ISSUE TITLE
완전탐색 boj 15651 질문드립니다!

### ISSUE THREAD

**Issue by jung-ho-kim** [rhs0266/FastCampus#58]
배열을 0번째가 아닌 1번째부터 쓰시는 이유가 따로 있을까요??

**Comment by rhs0266** [comment]
그거슨 개인의 차이 같습니다. 저는 c++을 사용하기도 하고, 대부분의 문제가 1번 부터 시작하는 것 때문에 습관적으로 그렇게 되었습니다!
