### ISSUE TITLE
안녕하세요 이분탐색 두용액 문제 질문 있습니다.

### ISSUE THREAD

**Issue by kamoo2** [rhs0266/FastCampus#59]
if(left  < result-1 && Math.abs(A[result - 1] + A[left]) < best_sum){
                best_sum = Math.abs(A[result-1] + A[left]);
                v1 = A[left];
                v2 = A[result-1];
            }

            if(result <= N &&  Math.abs(A[result] + A[left]) < best_sum){
                best_sum = Math.abs(A[result] + A[left]);
                v1 = A[left];
                v2 = A[result];
            }
이 코드에서 위 조건문의 left < result-1 이라는 범위를 설정해주는 이유에 대해서 궁금합니다. 
이 범위를 설정해주지 않으면 문제가 틀리던데 어떤 이유 때문인가요 ?

**Comment by rhs0266** [comment]
result는 left 보다 큰 게 보장되지만, result-1 은 보장되지 않아서 그런데요, "서로 다른 두 용액"을 골라야 하는 조건을 위해 꼭 필요합니다.

2
0 1

이와 같은 조건에서 정답이 올바르게 나오지 않을 것 같습니다.

**Comment by kamoo2** [comment]
감사합니다 !
