### ISSUE TITLE
백준 2559번 수열 문제 질문 있습니다. 

### ISSUE THREAD

**Issue by kamoo2** [rhs0266/FastCampus#60]
static int N,K;
    static int[] A;
    static void input(){
        N = sc.nextInt();
        K = sc.nextInt();
        A = new int[N+1];
        for(int i=1;i<=N;i++){
            A[i] = sc.nextInt();
        }
    }

    static void pro(){
        int R = 0,sum=0,max = Integer.MIN_VALUE;
        for(int L = 1;L<=N;L++){
            sum-= A[L-1];
            while(R+1 <= N && R-L+1<K){
                sum += A[++R];
            }
            max = Math.max(max,sum);
        }

        System.out.println(max);
    }

    public static void main(String[] args) {
        input();
        pro();
    }

계속 백준에서 틀렸다고 나와서 계속 생각해도 이해가 되질 않습니다. 
타입 문제도 아니라고 생각하는데 
어느 부분을 잘 못 했는지 알 수 있을까요 ??

**Comment by rhs0266** [comment]
지금 코드 대로면, `L`이 `N`에 가까워진 순간에는 `L ~ R` 구간의 길이가 `K`가 아닐 수도 있지 않을까 싶습니다.

좀 더 고민해보시다가 모르시겠으면 아래 예제를 봐보세요.

<스포주의>

5 2
-1 -1 -1 -1 -1
