### ISSUE TITLE
안녕하세요. 15651 [n과 n (3)] 코드 질문 있습니다.

### ISSUE THREAD

**Issue by zzoyeon9** [rhs0266/FastCampus#61]
선생님께서 짠 코드와 제가 짜본 코드의 구조가 거의 동일했는데 제 코드는 백준에서 시간 초과가 뜨더군요. 원인을 분석해보니 다름 아닌 '출력' 과정에서의 문제였는데요, 이해가 안가는 부분이 있어서 질문을 드렸습니다.

먼저, 선생님과 갈린 코드 부분은 이렇습니다.

```
        if(count==m) { //m개로 이루어진 수열을 완성하였을 때
            for (int i=0;i<m;i++)
                System.out.print(seq[i] + " ");
            System.out.println();
            return;
        }
```

여기서 시간초과의 원인으로 의심한 부분은 아래와 같습니다.

**1. 매 해가 구해질때마다 배열 요소 하나하나 + " "를 반복해서 출력하는 방식** 
**2. System.out.print 메서드의 내부로직 상의 느림**  

하지만 이해가 되지 않는 점은 각각 이렇습니다.

전자라 했을 경우, sb.append 명령이 print 명령으로 바뀌었을 뿐, **반복 및 연산 횟수에 있어서는 달라진 점이 없는데** 
1초에 1억번 연산이라고 가정했을 시, 해당 문제의 시간 제한 1초는 아주 넉넉하다고 생각하기 때문입니다. (실제로 코드를 돌려봐도 1초보다 엄청 오래걸리긴 하는데 정확한 이유는 모르겠습니다.)

후자라 했을 경우, 출력 메소드에 따라 성능 차이가 저렇게 드라마틱하게 차이나진 않을 것이라고 생각했기 때문입니다.

아니면 제가 놓친 또다른 원인이 있는걸까요?

**Comment by rhs0266** [comment]
안녕하세요 @zzoyeon9 님

java나 C++이나 모두 "빠른 입력, 빠른 출력"이 존재합니다. 그런 이름이 붙은 것부터 속도에 유의미한 차이가 있는 거겠죠?

작성해주신 코드의 주된 범인은 `System.out.print()` 가 맞습니다. Operating System / System Programming 에 대한 지식이 얼마나 되시는 지 몰라 간단하게 설명 드리면, 출력 요청이 일어날 때마다 발생하는 system call interruption 이 프로그램 수행 시간에 매우 큰 영향을 미칩니다.

정답 코드에서는 문자열을 전부 building 한 다음에 **단 한 번 출력 요청**을 하는 반면, 작성해주신 코드는 그렇지 않고 **매 숫자 마다** 출력 요청을 하고 계세요. 이 때문에 "빠른 출력"이라는 이름으로 string builder를 씁니다.
