### ISSUE TITLE
백준 14888 문제의 해결이 되지 않습니다.

### ISSUE THREAD

**Issue by khs0806** [rhs0266/FastCampus#66]
```
static void goohyun(int k, int val) {
        //System.out.println("k,val,N " + k + " " + val + " " + N);
        if (k == N-1) {
            System.out.println("val fin "+val);
            min = Math.min(min, val);
            max = Math.max(max, val);
        } else {
            for (int i=0; i<4; i++) {
                System.out.println("operater["+i+"] " + operaters[i]);
                if (operaters[i] > 0) {
                    System.out.println("val " + val);
                    if (i == 0) val = val + nums[k+1];
                    if (i == 1) val = val - nums[k+1];
                    if (i == 2) val = val * nums[k+1];
                    if (i == 3) val = val / nums[k+1];
                    operaters[i]--;
                    goohyun(k+1, val);
                    operaters[i]++;
                }
            }
        }
    }
```

문제풀이를 보기전에 혼자 구상해서 풀이를 해봤는데
해당 연산자가 1개이상 있을때만 연산되게 끔 해놓아서
문제가 풀릴거같은데 도저히 디버깅 해봐도 안풀리네요..
어디서 꼬이는지 모르겠어서 질문올립니다.ㅠ

**Comment by rhs0266** [comment]
새로운 연산자를 선택해서 도전할 때마다 val 값이 바뀌고 있네요. operators[i]--, ++ 해주신 것처럼, 재귀 호출이 끝난 뒤에 val 값이 변하면 안되겠죠?

                    System.out.println("val " + val);
                    int new_val = 0;
                    if (i == 0) new_val = val + nums[k+1];
                    if (i == 1) new_val = val - nums[k+1];
                    if (i == 2) new_val = val * nums[k+1];
                    if (i == 3) new_val = val / nums[k+1];
                    operaters[i]--;
                    goohyun(k+1, new_val);
                    operaters[i]++;
                    
요러케 바꿔보시겠어요?
