### ISSUE TITLE
백준7795번(먹을 것인가 먹힐 것인가) 질문 있습니다.

### ISSUE THREAD

**Issue by jiwon83** [rhs0266/FastCampus#67]
안녕하세요, 강의 너무 잘 듣고 있습니다! 

 **이분탐색 - 백준 7795번**을 강사님 코드를 베이스로 풀었는데 궁금한 점이 있어 질문 드립니다. 
강사님 코드에서 
`            if (B[mid] == x){
                num = mid - 1;
                break;
            }`
을 **lower_bound()의 while문 안**에 추가했는데 **체점 결과 틀렸다고 뜹니다**_.
 만약 A 배열의 (비교하려는 값) X 와 B배열의 중간인덱스(mid)가 같다면 mid-1을 리턴_하면 되지 않는 걸까요? 
예시 입출력은 정답 값이 잘 나오는데 맞지 못해서 궁금해서 여쭤봅니다...!! 

`static int lower_bound(int [] B, int L,int R, int x){
        int num = L-1;
        while (L <= R){
            int mid = (L + R) / 2;

            if (B[mid] == x){
                num = mid - 1;
                break;
            }`
            if (B[mid] < x){ 
                num = mid;
                L = mid + 1;
            }else if ( B[mid] >= x){ 
                R = mid - 1;
            }
        }
        return num;
    }`

**Comment by rhs0266** [comment]
안녕하세요 @jiwon83 님 :) 감사합니다 ㅎㅎ

같은 값이 여러 개 있는 경우가 문제인 케이스 입니다. 예를 들어 `B = {1, 2, 2 ,2 ,2 2, 2, 2, 2 ,2, 2, 3}` 인데 여기서 `x=2`에 대해 lower bound를 구하고 싶다고 해보겠습니다. 그럼 저희가 기대하는 값은 "제일 왼쪽 2"의 위치인데, mid 에서 운 좋게 2를 찾았다고 해도 그 왼쪽에 2가 더 많이 있을 수도 있겠죠?

그래서 2를 찾더라도, 왼쪽에 더 있을 수 있기 때문에 while 문을 계속 반복하면서 "진짜 제일 왼쪽 2"를 찾아주는 코드입니다.

**Comment by jiwon83** [comment]
> 2, 빠른 답변 너무 감사드립니다 !! 쉽게 설명해주셔서 완전히 이해됐어요 !! 예외 케이스 생각하는 게 아직은 어렵네요ㅠ!! 덕분에 이해됐습니다 감사합니다 : )
