### ISSUE TITLE
1697번 문제 visit[], dist[]의 크기가 10005인 이유가 궁금합니다.

### ISSUE THREAD

**Issue by intrager** [rhs0266/FastCampus#68]
안녕하세요. 강의 매번 잘 듣고 있습니다. 호석님 덕분에 매번 알고리즘 역량이 성장함을 느끼고 있습니다.

다름이 아니라,
1697번 숨바꼭질 문제에서 수빈이와 동생의 범위는 각각 100,000 미만까지입니다.
이때 배열을 100,005(십만 오)로 선언하신 이유가 궁금합니다.

감사합니다😊

**Comment by rhs0266** [comment]
안녕하세요 :)

제 습관 중 하나입니다. 배열에 잘못 접근하는 상황을 if문으로 매번 예외 처리하기 싫어서 tolerant하게 좀 넉넉하게 잡아준 것입니다. 이러면 `arr[i+1]` 등을 코드에 작성 할 때, `if (i + 1 <= N) ~~ else ~~` 를 안 적어도 되서 편하더라구요.

**Comment by intrager** [comment]
감사합니다 !
