### ISSUE TITLE
BOJ2597 계단오르기 질문 드립니다

### ISSUE THREAD

**Issue by NohEunSeok** [rhs0266/FastCampus#70]
안녕하세요 강사님 
강의 잘 듣고있습니다.

강의 중 초기화 관련 부분에서 이해가 안가는 부분이 있어서 질문 드립니다.

코드에서는 Dy[1][1]에 초기화를 해주셨는데 

그림에서는 Dy[1][0]에 10이 입력 되어있습니다.

코드와 그림이 차이가 있어 질문 드립니다.

감사합니다.

Dy[1][0] = 0;
Dy[1][1] = A[1];

if (N >= 2){
    Dy[2][0] = A[2];
    Dy[2][1] = A[1] + A[2];
}

![image](https://user-images.githubusercontent.com/63040475/206976286-81fec4e9-c782-4ccc-a820-3cb512eb6e64.png)

**Comment by rhs0266** [comment]
앗 그림이 잘못 된 것이 맞습니다. 감사합니다 :)
