### ISSUE TITLE
알고리즘 유형별 풀이 강의를 듣고나서 궁금한점들 문의드립니다.

### ISSUE THREAD

**Issue by momo1108** [rhs0266/FastCampus#71]
안녕하세요 강사님. 알고리즘 관련 강의를 듣고있는 수강생입니다.
좋은 강의 컨텐츠에 감사드립니다.
강의를 따라가며 궁금한 점이 생겨서 문의드립니다.

## BOJ 2011번 문제 - 암호코드(DP)
해당 문제의 정답 소스코드가 백준에서 오답처리가 됩니다.
반례를 찾아본 결과 입력값이 1203인 경우 `1 / 20 / 3` 가 유일한 경우의 수라 `1`이 정답으로 나와야 하는데,
정답코드로는 해석을 할 수 없는 경우인 `0`으로 출력이 됩니다.

## DP 유형의 추천 연습 문제 중 정답코드를 찾을 수 없는 문제들이 있습니다.
BOJ 11049 - 행렬곱셈순서
BOJ 10942 - 팰린드롬?
BOJ 1509 - 팰린드롬 분할 
위 문제들의 정답코드가 없는 것 같습니다.

**Comment by rhs0266** [comment]
오우... 고치겠습니다 감사합니다.

**Comment by rhs0266** [comment]
혹시 틀린 부분을 찾으시거나 정답 코드를 작성해보고 싶으시면 PR 편하게 날려주세요 :) 코드 리뷰도 해드릴게요!

**Comment by momo1108** [comment]
네 감사합니다! ^^

**Comment by rhs0266** [comment]
@momo1108  2011 번 무슨 코드가 오답 처리 되나요? 저는 [이 곳의 모든 코드](https://github.com/rhs0266/FastCampus/tree/main/%EA%B0%95%EC%9D%98%20%EC%9E%90%EB%A3%8C/02-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98/15~17-%EB%8F%99%EC%A0%81%20%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D/%EB%AC%B8%EC%A0%9C%EB%B3%84%20%EC%BD%94%EB%93%9C/2011-%EC%95%94%ED%98%B8%EC%BD%94%EB%93%9C)가 다시 제출해도 전부 정답으로 나옵니다.

**Comment by momo1108** [comment]
> @momo1108 2011 번 무슨 코드가 오답 처리 되나요? 저는 [이 곳의 모든 코드](https://github.com/rhs0266/FastCampus/tree/main/%EA%B0%95%EC%9D%98%20%EC%9E%90%EB%A3%8C/02-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98/15~17-%EB%8F%99%EC%A0%81%20%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D/%EB%AC%B8%EC%A0%9C%EB%B3%84%20%EC%BD%94%EB%93%9C/2011-%EC%95%94%ED%98%B8%EC%BD%94%EB%93%9C)가 다시 제출해도 전부 정답으로 나옵니다.

제가 확인한바로는 java 코드였습니다. 백준 2011번 문제 코드 제출 시 오답처리가 나서 반례를 찾아봤습니다 ^^

**Comment by rhs0266** [comment]
https://www.acmicpc.net/source/share/01e11145c4ac46bc99c816bb484855c0

뭐지.. 저는 제출해도 맞던데 ㅜㅜㅜ

**Comment by momo1108** [comment]
> https://www.acmicpc.net/source/share/01e11145c4ac46bc99c816bb484855c0
> 
> 뭐지.. 저는 제출해도 맞던데 ㅜㅜㅜ

아하 공유해주신 소스는 보니까 초기값 설정 부분에 코드가 제대로 들어가있네요.
정답코드링크쪽에는 초기값설정 부분 코드가 빠져있습니다.

**Comment by rhs0266** [comment]
엇! 버그인가..! 고쳐둘게요! 감사합니다.
