### ISSUE TITLE
BOJ15991 1,2,3 더하기 - 6 문제 질문 드립니다

### ISSUE THREAD

**Issue by NohEunSeok** [rhs0266/FastCampus#72]
안녕하세요  류호석 강사님

풀이 중 홀수 개를 더한 경우의 코드를 이해하지 못해서 질문 드립니다.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/EUNSEO~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/EUNSEO~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>

<body link="#0563C1" vlink="#954F72">

n=0 | 1 | 2 | 3 | 4
-- | -- | -- | -- | --
1 | 1 | 1+1 | 1+1+1 | 1+1+1+1
  |   | 2 | 3 | 1+2+1
  |   |   |   | 2+2
dy[0] | dy[1] | dy[2] | dy[3] | dy[4]
1 | 1 | 2 | 2 | 3
</body>

</html>

이 문제를 파티셔닝을 하게 되면 가운데 숫자를 기준으로 맨 앞뒤에 1,2,3이 붙게되는 것으로 생각됩니다.

이 때 n=4일 때 홀수 개를 더하기 위한 코드에서 mid가 2일 경우 Dy[(x - mid) / 2]가  Dy[1]로 되고

Dy[1]의 덧셈식은 1인데 해당 값을 어떤 이유로 더해주는 지 궁금합니다. (n=4 : 2+2 덧셈식과 대응이 안되는 것으로 생각되서요)

감사합니다~~

```
// 홀수 개를 더한 경우
 for (int mid = 1; mid <= 3; mid++)  // 가운데에 mid 를 더한 상황
        if (x - mid >= 0 && (x - mid) % 2 == 0) {  // 양쪽이 대칭을 이루게 더하기 위함
            res += Dy[(x - mid) / 2];
            res %= MOD;
        }

// 짝수 개를 더한 경우 (사실상 위에서 mid 가 0 인 경우. 즉, for loop을 0 부터 시작해도 됨)
if (x % 2 == 0) {  // 양쪽이 대칭을 이루게 더하기 위함
    res += Dy[x / 2];
    res %= MOD;
}
```

**Comment by rhs0266** [comment]
4=2+2  로 표현한 값은 짝수 개를 더한 경우에서 카운트 됩니다. (2+2 는 두 개의 수가 더해졌기 떄문입니다.)

홀수개의 수를 더해서 `x`를 만들기 위해서는, 가운데에 mid 라는 수가 더해지고 그 양쪽이 대칭이어야 합니다. 즉, `(Something) + mid + (Something의 대칭) = x` 인 식의 개수를 구해야 합니다. 식을 정리해보면 `Something = (x - mid) / 2` 을 만드는 경우의 수를 알아야 합니다. 때문에 그러한 경우의 수가 이미 계산되어 있는 `Dy[(x - mid) / 2]` 의 값을 가져오는 것입니다.

**Comment by NohEunSeok** [comment]
드디어 깨우쳤습니다 답변 감사합니다!!
