### ISSUE TITLE
01~02-완전 탐색/문제별 코드/15663-N과 M(9) 질문드립니다. 

### ISSUE THREAD

**Issue by mgKim7** [rhs0266/FastCampus#74]
올려주신 코드에서
` static void rec_func(int k) {
        if (k == M + 1) { // 1 ~ M 번째를 전부 다 골랐다!
            // selected[1...M] 배열이 새롭게 탐색된 결과

            for (int i = 1; i <= M; i++) sb.append(selected[i]).append(' ');
            sb.append('\n');
        } else {
            int last_cand = 0;
            for (int cand = 1; cand <= N; cand++) {
                if (used[cand] == 1) continue;
                if (nums[cand] == last_cand) continue;

                last_cand = nums[cand];
                selected[k] = nums[cand]; used[cand] = 1;
                rec_func(k + 1);
                selected[k] = 0; used[cand] = 0;
            }
        }
    }`
 if (used[cand] == 1) continue;
 if (nums[cand] == last_cand) continue;
이 부분이 잘 이해가 되지 않습니다.

**Comment by rhs0266** [comment]
`used` 배열이 가지는 의미와 `nums` 배열이 가지는 배열의 의미를 말로 설명해보실 수 있으실까요?

**Comment by mgKim7** [comment]
used 배열은 한번 선택했던 것을 또 선택 하는 것을 방지하기 위해 선언한거 같습니다. 그래서 선택한 숫자에 숫자를 매치시켜서(인덱스) 만약 인덱스가 같다면 다음 숫자로 넘어가게 하는 것 같습니다.  또 nums[cand]는  중복되는 수열을 또 출력하는 것을 방지하기 위해 선언한 것 같습니다. 그래서 마지막에 선택한 수를 nums[cand]에 넣어주어 다음 재귀를 할때 비교하여 같다면 다음 수로 넘어가는 것 같습니다. 제가 이해한 것이 맞을까요??

**Comment by mgKim7** [comment]
> `used` 배열이 가지는 의미와 `nums` 배열이 가지는 배열의 의미를 말로 설명해보실 수 있으실까요?

used 배열은 한번 선택했던 것을 또 선택 하는 것을 방지하기 위해 선언한거 같습니다. 그래서 선택한 숫자에 숫자를 매치시켜서(인덱스) 만약 인덱스가 같다면 다음 숫자로 넘어가게 하는 것 같습니다. 또 nums[cand]는 중복되는 수열을 또 출력하는 것을 방지하기 위해 선언한 것 같습니다. 그래서 마지막에 선택한 수를 nums[cand]에 넣어주어 다음 재귀를 할때 비교하여 같다면 다음 수로 넘어가는 것 같습니다. 제가 이해한 것이 맞을까요??

**Comment by rhs0266** [comment]
`used` 배열은 잘 이해하셨네요. 한 번 사용된 친구를 다시 나열하지 않기 위함이죠.

`nums` 배열은 입력 받은 배열을 정렬한 것입니다. 함수 `rec_func(int k)` 는 `k`번 인덱스에 올 수 있는 모든 선택지를 전부 수행해보면서 모든 순열을 찾아주는 역할을 가집니다. 그러려면 `k`번 인덱스에 올 수 있는 모든 수가 한 번 씩 놓아져야겠죠?

예를 들면 `nums[] ={1, 1, 1, 3, 3, 6, 6, 6}` 인 상태에서 `rec_func(1)` 가 호출된 상황이라고 하겠습니다. 그러면 1번 인덱스에 어떤 친구를 나열해 봐야 하는 지 모두 시도하겠죠? 근데 이 때 8가지 수를 한 번 씩 다 시도해보면 `1`도 세 번이나 시도하고, `3`은 두 번이나 시도하고, `6`도 세 번이나 시도하겠죠?

하지만 현실적으로는 `1, 3, 6`을 한 번 씩만 시도해보면 모든 순열을 찾을 수 있습니다. 따라서 `last_cand` 가 "마지막으로 시도했던 수"를 의미하도록 설정해두어서, `if (nums[cand] == last_cant) continue` 부분은 똑같은 수를 중복해서 시도하지 않기를 바라는 것입니다.

**Comment by mgKim7** [comment]
> `used` 배열은 잘 이해하셨네요. 한 번 사용된 친구를 다시 나열하지 않기 위함이죠.
> 
> `nums` 배열은 입력 받은 배열을 정렬한 것입니다. 함수 `rec_func(int k)` 는 `k`번 인덱스에 올 수 있는 모든 선택지를 전부 수행해보면서 모든 순열을 찾아주는 역할을 가집니다. 그러려면 `k`번 인덱스에 올 수 있는 모든 수가 한 번 씩 놓아져야겠죠?
> 
> 예를 들면 `nums[] ={1, 1, 1, 3, 3, 6, 6, 6}` 인 상태에서 `rec_func(1)` 가 호출된 상황이라고 하겠습니다. 그러면 1번 인덱스에 어떤 친구를 나열해 봐야 하는 지 모두 시도하겠죠? 근데 이 때 8가지 수를 한 번 씩 다 시도해보면 `1`도 세 번이나 시도하고, `3`은 두 번이나 시도하고, `6`도 세 번이나 시도하겠죠?
> 
> 하지만 현실적으로는 `1, 3, 6`을 한 번 씩만 시도해보면 모든 순열을 찾을 수 있습니다. 따라서 `last_cand` 가 "마지막으로 시도했던 수"를 의미하도록 설정해두어서, `if (nums[cand] == last_cant) continue` 부분은 똑같은 수를 중복해서 시도하지 않기를 바라는 것입니다.

답변 감사합니다
