### ISSUE TITLE
배열과 리스트의 차이

### ISSUE THREAD

**Issue by dduckmane** [rhs0266/FastCampus#76]
좋은 강의 잘 수강 하고 있습니다.
강의를 수강하던 도중 궁금증이 생겨 질문합니다.

강사님은 주로 list(ex) arrayList) 를 사용하시기 보단 배열(ex) int[] a) 을 사용하시는 것 같습니다.

혹시 이 부분이 특정 이유가 있는 건가요??

예를 들어 리스트 보단 배열이 시간 복잡도나 공간 복잡도 측면에서 유리한가요??

**Comment by rhs0266** [comment]
제가 익숙하기도 하고, 기능이 많을수록 느리기 때문입니다. 저한테 필요한 연산은 int[] 만으로도 충분히 커버되는데 굳이 더 많은 기능을 제공하면서 느린 친구를 사용할 필요가 없었습니다.

**Comment by dduckmane** [comment]
감사합니다.
