### ISSUE TITLE
Dijkstra - 최소비용구하기

### ISSUE THREAD

**Issue by SongJwans** [rhs0266/FastCampus#77]
수업에서 하신 백준의 1916_ 최소비용구하기 문제를 푸는데 
수업에서 하신 코드로 문제를 하다가 궁금한 점이 생겨서 글을 남깁니다. 

아래는 
아래는 백준 문제에서 주어진 예제 입력 1 입니다.

5
8
1 2 2
1 3 3
1 4 1
1 5 10
2 4 2
3 4 1
3 5 1
4 5 3
1 5

에서 마지막에 입력하는 1 과 5 우리가 구하고자하는 출발점의 도시번호와 도착점의 도시번호입니다. 

정확하게 잘 돌아가는지 확인해보기 위해서 다른 값(1 4)도 입력해본결과 

pro()  에 dist[end] 에서 ArrayIndexOutOfBoundsException  : Index 55 out of bounds for length 6 이 뜹니다. 

그런데  또 그냥 dist[] 배열 전체를 출력하는건 잘 됩니다. 이유가 뭔지 궁금합니다.

**Comment by rhs0266** [comment]
정확히 입력을 어떻게 하셨나요?

**Comment by SongJwans** [comment]
5
8
1 2 2
1 3 3
1 4 1
1 5 10
2 4 2
3 4 1
3 5 1
4 5 3
1 4

마지막 end 값만 바꿔서 했습니다.

**Comment by SongJwans** [comment]
5
8
1 2 2
1 3 3
1 4 1
1 5 10
2 4 2
3 4 1
3 5 1
4 5 3
1 5

위 값을 복사한 후 입력창에서  마지막 값 end (5)를 다른 정점으로 바꿨을 때 안됐는데

아래를 입력을 복사하니까 해결했습니다.

5
8
1 2 2
1 3 3
1 4 1
1 5 10
2 4 2
3 4 1
3 5 1
4 5 3
1 3 

처음부터 원하는 값을 복사하면 되네요 
그냥 버그인거 같습니다.  대답해주셔서 감사합니다.
