### ISSUE TITLE
백준 1806 문제 시간복잡도 관련 질문입니다.

### ISSUE THREAD

**Issue by dduckmane** [rhs0266/FastCampus#79]
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/108928206/213842660-a7c123fd-f975-4734-8017-290fc40af5a6.png">
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/108928206/213842674-3d56e606-6f17-4d4c-97cc-e8c7b2d753f8.png">

- 이 문제의 시간 복잡도를 N 이라고 설명해주셨습니다.
- L 이  N번 만큼 움직이고 R이 N 번 만큼 움직여서 총 2N이여서 시간복잡도가 O(N) 이 되는 건가요??

**Comment by rhs0266** [comment]
네 맞습니다!
