### ISSUE TITLE
정렬 강의 부분이 보이질 않아 질문드립니다.

### ISSUE THREAD

**Issue by java-saeng** [rhs0266/FastCampus#8]
안녕하십니까 정렬 부분 강의를 듣고 싶은데 github에 올려져있는 정렬 부분은 강의에서 찾아볼 수 없어 질문드립니다.. 
다양한 정렬 응용법 강의에서 N-Queen 문제와 부분 수열의 합 문제가 끝나고 바로 이분 탐색 강의인데 정렬 부분이 보이질 않습니다ㅠㅠ

**Comment by rhs0266** [comment]
안녕하세요. 감사합니다 확인 요청 드렸습니다!
