### ISSUE TITLE
그래프의 시간 복잡도

### ISSUE THREAD

**Issue by dduckmane** [rhs0266/FastCampus#81]
1. 시간 복잡도와 상수 질문
<img width="995" alt="image" src="https://user-images.githubusercontent.com/108928206/214463725-577f76ec-b4a2-44ba-bca1-2bbcaf2d5584.png">

이제 이전 강의에서 인접 리스트에 시간 복잡도는 O(E) 라고 배웠습니다. 이것도 모든 차수를 다 더하면 2*E 가 나오고 시간 복잡도를 계산하면 상수는 지워지므로 시간복잡도는 O(E)라고 배웠습니다.

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/108928206/214463524-b5fbd500-612f-415f-9956-a5369c4fda9a.png">

- 이문제에서의 간선은 4*N ^2 이라고 설명해주셨는데
- 그럼 이전 강의 내용이랑 합쳐보면 총 시간 복잡도는 2*(4*N의 제곱) 인데 이것도 빅오표기법으로하면 앞의 상수 8이 날라가서 시간 복잡도가 N의 제곱이 되는건가요??
- 빅오 표기법으로 하면 앞의 상수가 얼마이든 다 날리는 건가요??

2. O(V+E) 와 O(E) 질문 
![image](https://user-images.githubusercontent.com/108928206/214497443-ef9162a4-4489-43c7-a4b4-1575f8a2e339.png)

- 그리고 여기서는 시간 복잡도가 O(V+E) 라고 배웠습니다.
- 그래프의 시간복잡도는 모든 간선을 다 더한 값이라고 배웠고 그래서 모든 간선의 합 = 2* E 어서 시간복잡도는 O(E) 인건 이해가 가는데
- 시간 복잡도가 O(V+E) 인 이유가 궁금합니다.

**Comment by rhs0266** [comment]
1. 네 맞습니다. O()의 정의에 따라서 상수 다 날려버려도 상관없고, 냅두셔도 상관없습니다.

2. 보통의 그래프에서는 V <= E 이기 때문에 O(E) 라고 쓰셔도 됩니다. 하지만 가끔은 V가 엄청 크고 E가 엄청 작을 수도 있기 때문에 안전하게 적어주는 게 좋습니다.

**Comment by dduckmane** [comment]
친절한 답변 감사드립니다!
근데 강의에서는 시간 복잡도가 O(V + E) 인 이유는 못 배운 거 같아서 재질문 드립니다.

강의에서는 간선의 합이 시간 복잡도가 되서 2* E 여서 시간 복잡도가 O(E)라고 배웠는데요
V는 왜 더해지는 건가요??

**Comment by rhs0266** [comment]
시작점이 V=100000 개 인데 간선은 0개인 그래프를 상상해보면, "모든 시작점을 전부 Queue에 넣는" 행위를 할 때 O(100000) 만큼의 시간을 소모하죠? 이 행위 또한 시간 복잡도 계산에 필요하기 때문입니다.

**Comment by dduckmane** [comment]
아 감사합니다!!
