### ISSUE TITLE
그래프 관련 질문입니다.

### ISSUE THREAD

**Issue by dduckmane** [rhs0266/FastCampus#84]
-1번 방식:  처음에 강의에서 그래프 관련 문제를 풀 때 인접리스트에 from 에 to 를 저장하고 to 에 from 을 저장햇습니다.

![image](https://user-images.githubusercontent.com/108928206/215254153-5423df4d-222b-4500-97de-779c7766fd33.png)

- 2번 방식: 하지만 계속 강의를 들으면서 그래프 관련문제들에 from 에 to 만 저장하는 방식이 많아졌습니다.

![image](https://user-images.githubusercontent.com/108928206/215254202-70a0af2b-7f3c-4c9b-85c2-411ba916e690.png)

- 그래서 저도 저만의 개념을 정리하고 있었는데 그래도 계속 햇갈려서 질문드립니다.
- 그래프 관련 문제를 풀 때 1번 방식으로 풀 때와 2번 방식으로 풀 때의 차이를 알려주시면 감사하겠습니다!
- (저는 그래프의 방향성 유무와 관련있다고 생각합니다.)

**Comment by rhs0266** [comment]
문제에 주어진 정보를 "간선"으로 변환해서 저장하고 계십니다. 그럼 문제에 주어진 정보에 맞춰지겠죠? 두 상태 `u`와 `v`에 대해서, `u`에서 `v`로 "단방향"으로 변화한다면 2번, 둘이 서로 변화가 가능하면 양방향이니까 1번 방법처럼 구현하시게 될 겁니다.

**Comment by dduckmane** [comment]
네 감사합니다.
