### ISSUE TITLE
[Two pointer 강의] 16472 고냥이 질문있습니다

### ISSUE THREAD

**Issue by hayeooo** [rhs0266/FastCampus#86]
안녕하세요
Two pointer 강의 고냥이 문제에서 오른쪽 포인터를 고정시키고 왼쪽 포인터를 알파벳 종류 개수에 맞도록 이동시킨다고 하셨는데,
반대일 경우에는 문제를 풀 수 없는지 궁금합니다.

저는 왼쪽 포인터를 고정시키고 오른쪽 포인터를 이동시킨 알고리즘을 구현하였는데
채점 과정에서 틀렸다고 나와서 다른 경우로 풀었을 때 예외 케이스가 존재하는 것인지 알고 싶습니다.

import sys
input = sys.stdin.readline

N = int(input())
string = input().strip()
alpha = [0]*26
R = -1
kind = 0
res = 0
for L in range(len(string)):
    while kind <= N and R < len(string)-1:
        R += 1
        alpha[ord(string[R])-ord('a')] += 1
        if alpha[ord(string[R])-ord('a')] == 1:
            kind += 1
    res = max(res, R-L)
    alpha[ord(string[L])-ord('a')] -= 1
    if alpha[ord(string[L])-ord('a')] == 0:
        kind -= 1

print(res)

**Comment by rhs0266** [comment]
Indent가 없으면 보기 힘듭니다 ㅜㅜ

아래 입력으 결과가 어떻게 나오시나요?
```
5
abc
```
