### ISSUE TITLE
백준 5639번 문제별 코드 정답 

### ISSUE THREAD

**Issue by dduckmane** [rhs0266/FastCampus#88]
https://github.com/rhs0266/FastCampus/blob/main/강의%20자료/02-알고리즘/12-트리/문제별%20코드/5639-이진%20검색%20트리/solution.java

여기 이부분 런타임 오류가 떠서 문의 드립니다

![image](https://user-images.githubusercontent.com/108928206/216753884-2f48e5b6-7321-431e-9e6d-974ddc0130b7.png)

정답 다시 올려주실 수 있나요??

**Comment by rhs0266** [comment]
해당 문제에 입력을 왜 "A B C" 로 작성하셨나요?

**Comment by dduckmane** [comment]
아 제가 잘못 봤네요
