### ISSUE TITLE
[백준 -2808] 나무 자르기 질문 드립니다!

### ISSUE THREAD

**Issue by her0807** [rhs0266/FastCampus#9]
안녕하세요 멘토님! 

문제 풀이를 하다  결과도 잘 나오고, 시간 복잡도도 초과하지 않는데 문제가 틀렸다고 나와서 답안과 비교해보니 
변수를 선언 할 때 `long` 이 아닌 `int` 로 선언해서 그랬던 거더라구요. 

연산을 할 때는 결국 Int 로 형변환을 해야하는데 long 을 사용해야하는 이유가 궁금합니다. 

감사합니다. 

```java
static boolean determination(int H) {
        // H 높이로 나무들을 잘랐을 때, M 만큼을 얻을 수 있으면 true, 없으면 false를 return하는 함수
        long sum = 0;
        for (int i = 1; i <= N; i++) {
            if (A[i] > H) {
                sum += A[i] - H;
            }
        }
        return sum >= M;
    }

    static void pro() {
        long L = 0, R = 2000000000, ans = 0;
        // [L ... R] 범위 안에 정답이 존재한다!
        // 이분 탐색과 determination 문제를 이용해서 answer를 빠르게 구하자!
        while (L <= R) {
            int mid = (int) ((L + R) / 2);
            if (determination(mid)) {
                ans = mid;
                L = mid + 1;
            } else {
                R = mid - 1;
            }
        }
        Syst
```

**Comment by rhs0266** [comment]
`L` 과 `R` 에 대한 이야기를 하시는 거라면, 둘을 더한 뒤에 2를 나눈 최종 결과는 20억 이하이므로 int이면 충분하지만 둘을 더한 결과가 20억을 넘을 수 있기 때문입니다.

연산자의 우선순위를 생각해서 해당 부분을 풀어 써보면,

X = L + R;
mid = X / 2;

이런 순서로 L+R 먼저 계산된 뒤의 결과를 L, R의 type인 int로 저장하는데, int 범위를 벗어나게 되면 문제가 생기는 것이지요.

L과 R이 모두 long 이라면 더한 값도 long으로 담기 때문에 문제가 생기지 않습니다.

**Comment by her0807** [comment]
아아 감사합니다!

너무 기초적인 질문을 드려서 죄송합니다. ㅠㅠㅠ

멘토님 강의 들으면서 처음으로 알고리즘 공부를 제대로 하는 느낌이 듭니다!

양질의 강의 해주셔서 감사합니다 :)

**Comment by rhs0266** [comment]
![image](https://user-images.githubusercontent.com/8068838/124441217-6d272380-ddb6-11eb-84ac-d15339ae23dd.png)
