### ISSUE TITLE
코데 관련 간단한 질문

### ISSUE THREAD

**Issue by dduckmane** [rhs0266/FastCampus#90]
강사님의 양질의 강의 잘 수강하고 있습니다.
다름이 아니라 이번에 이제 류호석배 모의고사 강의를 수강하고 있는데요
간단한 궁금증이 생겨서요

1. 코테 볼 때 툴은 어떤걸 사용하나요?? 자유인가요?? 저는 인텔리제이 사용하는 데 사용가능한가 싶어서요
2. 그리고 총 5문제 5시간에 풀라고 하셨는데 보통 코테 시험장에서도 1문제 1시간가량의 시간을 주나요??
3. 또한 물론 코테시험마다 다르겠지만 주로 오픈 인터넷 시험인가요??
4. 부분점수의 기준이 궁금합니다. 일단은 기존 백준문제처럼 모든 테스트 케이스를 통과해서 정답은 맞아야 점수가 들어가는 건가요??
     결론은 문제의 정답은 맞고 시간 초과인 경우에만 부분점수가 들어가는건가요??

**Comment by rhs0266** [comment]
1. 시험마다 다릅니다. IDE 를 못 쓰는 경우 웹 상에서 바로 코드를 작성하고 실행해보는 방법을 채택합니다. 프로그래머스 사이트 경험을 추천드려요!
2. 편차가 크지만 평균적으로 그렇습니다
3. 기본적으로 클로즈 인터넷이라고 생각하시는 게 좋습니다
4. 코테마다 다릅니다. 코테 운영 회사 측에 질문하셔야 합니다!
