### ISSUE TITLE
다이나믹 프로그래밍2 강의 - 백준 2579 에 대해 질문이 있습니다.

### ISSUE THREAD

**Issue by zaien24** [rhs0266/FastCampus#91]
질문 드립니다. 시간 되실 때 답변 부탁드립니다~

[질문1]
강의 위치 : 11:10 
계단 올라는 오는 것에 대한 그림 그리며 설명을 했는데요

i-1 번째 밟고 i 번째 도착 할 경우 가 Dy[i][1] 에 빨간색으로 표시하면서 설명하고, 
i-1 번째 밟지않고 i 번째 도착 할 경우 가 Dy[i][0] 에 빨간색으로 표시하면서 설명하자는 의도가 맞는지요?

**Comment by zaien24** [comment]
https://github.com/rhs0266/FastCampus/issues/70

**Comment by rhs0266** [comment]
네 맞습니다! 정확하십니다 👍
