### ISSUE TITLE
코테 연습 중 막힐 때 노하우 질문드립니다

### ISSUE THREAD

**Issue by diiiiiiiino** [rhs0266/FastCampus#93]
안녕하세요 강사님
문제 해결 중 도저히 해결 방안이 떠오르지 않을 때 
문제 풀이 후 다른 분의 문제 풀이를 본다던지 또는 끝까지 혼자힘으로 풀어낸다
어떤식으로 문제를 풀어야 할지 질문 드립니다.

**Comment by rhs0266** [comment]
다른 풀이를 보는 게 절대 잘못된 게 아닙니다. 잘못된 것은 그 풀이를 자기 것으로 안 만들고 넘어가는 게 문제입니다. 꼭 자기 힘으로 다시 풀 수 있을 때까지 공부하세요!
