### ISSUE TITLE
c++ 답안에서 배열들 선언하실때 크기

### ISSUE THREAD

**Issue by Hjanice** [rhs0266/FastCampus#98]
c++ 답안에서 배열들 선언하실때 전역변수로 선언하면서 입력N의 최대값+5 로 하시던데 +5해주시는 이유가 있나요?

ex. N의 최대값이 50이라면  
#define NM 55 
이런식으로 50이 아니라 55로 하시는이유가 궁금합니다.

**Comment by rhs0266** [comment]
문제를 풀다보면 종종 N+2, N+3 번지에 접근할 일이 있다보니 항상 마음의 여유를 가지고 5 정도 추가하는 편입니다. 개인적인 취향이니 바꾸셔도 돼요!

**Comment by Hjanice** [comment]
답변감사합니다 
강의 덕분에 코드를 짜기전에 계산을 해보고 구조화하면서 스케치하는 과정을 자연스럽게 배우게 되니 도움이 많이 되었습니다.
운이 좋아 질좋은 강의를 듣게 되었네요.
